/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RecallsRouteImport } from './routes/recalls'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OrdonnancesRouteImport } from './routes/ordonnances'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CertificatsMedicauxRouteImport } from './routes/certificats-medicaux'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallsRoute = RecallsRouteImport.update({
  id: '/recalls',
  path: '/recalls',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdonnancesRoute = OrdonnancesRouteImport.update({
  id: '/ordonnances',
  path: '/ordonnances',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatsMedicauxRoute = CertificatsMedicauxRouteImport.update({
  id: '/certificats-medicaux',
  path: '/certificats-medicaux',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/certificats-medicaux': typeof CertificatsMedicauxRoute
  '/login': typeof LoginRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/patients': typeof PatientsRoute
  '/payments': typeof PaymentsRoute
  '/recalls': typeof RecallsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/certificats-medicaux': typeof CertificatsMedicauxRoute
  '/login': typeof LoginRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/patients': typeof PatientsRoute
  '/payments': typeof PaymentsRoute
  '/recalls': typeof RecallsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/certificats-medicaux': typeof CertificatsMedicauxRoute
  '/login': typeof LoginRoute
  '/ordonnances': typeof OrdonnancesRoute
  '/patients': typeof PatientsRoute
  '/payments': typeof PaymentsRoute
  '/recalls': typeof RecallsRoute
  '/reviews': typeof ReviewsRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/certificats-medicaux'
    | '/login'
    | '/ordonnances'
    | '/patients'
    | '/payments'
    | '/recalls'
    | '/reviews'
    | '/settings'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/certificats-medicaux'
    | '/login'
    | '/ordonnances'
    | '/patients'
    | '/payments'
    | '/recalls'
    | '/reviews'
    | '/settings'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/certificats-medicaux'
    | '/login'
    | '/ordonnances'
    | '/patients'
    | '/payments'
    | '/recalls'
    | '/reviews'
    | '/settings'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CertificatsMedicauxRoute: typeof CertificatsMedicauxRoute
  LoginRoute: typeof LoginRoute
  OrdonnancesRoute: typeof OrdonnancesRoute
  PatientsRoute: typeof PatientsRoute
  PaymentsRoute: typeof PaymentsRoute
  RecallsRoute: typeof RecallsRoute
  ReviewsRoute: typeof ReviewsRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recalls': {
      id: '/recalls'
      path: '/recalls'
      fullPath: '/recalls'
      preLoaderRoute: typeof RecallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordonnances': {
      id: '/ordonnances'
      path: '/ordonnances'
      fullPath: '/ordonnances'
      preLoaderRoute: typeof OrdonnancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificats-medicaux': {
      id: '/certificats-medicaux'
      path: '/certificats-medicaux'
      fullPath: '/certificats-medicaux'
      preLoaderRoute: typeof CertificatsMedicauxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  CertificatsMedicauxRoute: CertificatsMedicauxRoute,
  LoginRoute: LoginRoute,
  OrdonnancesRoute: OrdonnancesRoute,
  PatientsRoute: PatientsRoute,
  PaymentsRoute: PaymentsRoute,
  RecallsRoute: RecallsRoute,
  ReviewsRoute: ReviewsRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
